// <auto-generated />
using System;
using Eddian_Vasquez_Ap1_p2.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eddian_Vasquez_Ap1_P2.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250715034945_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eddian_Vasquez_Ap1_p2.Models.Entrada", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntradaId"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<double>("PesoTotal")
                        .HasColumnType("float");

                    b.HasKey("EntradaId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("Eddian_Vasquez_Ap1_p2.Models.EntradaDetalle", b =>
                {
                    b.Property<int>("EntradaDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntradaDetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("EntradaId")
                        .HasColumnType("int");

                    b.Property<double>("PesoEntrada")
                        .HasColumnType("float");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("EntradaDetalleId");

                    b.HasIndex("EntradaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("EntradasDetalle");
                });

            modelBuilder.Entity("Eddian_Vasquez_Ap1_p2.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EsCompuesto")
                        .HasColumnType("bit");

                    b.Property<int>("Existencia")
                        .HasColumnType("int");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Descripcion = "Maní",
                            EsCompuesto = false,
                            Existencia = 100,
                            Peso = 0.0
                        },
                        new
                        {
                            ProductoId = 2,
                            Descripcion = "Pistachos",
                            EsCompuesto = false,
                            Existencia = 100,
                            Peso = 0.0
                        },
                        new
                        {
                            ProductoId = 3,
                            Descripcion = "Almendras",
                            EsCompuesto = false,
                            Existencia = 100,
                            Peso = 0.0
                        },
                        new
                        {
                            ProductoId = 4,
                            Descripcion = "Frutos Mixtos 200gr",
                            EsCompuesto = true,
                            Existencia = 0,
                            Peso = 200.0
                        },
                        new
                        {
                            ProductoId = 5,
                            Descripcion = "Frutos Mixtos 400gr",
                            EsCompuesto = true,
                            Existencia = 0,
                            Peso = 400.0
                        },
                        new
                        {
                            ProductoId = 6,
                            Descripcion = "Frutos Mixtos 600gr",
                            EsCompuesto = true,
                            Existencia = 0,
                            Peso = 600.0
                        });
                });

            modelBuilder.Entity("Eddian_Vasquez_Ap1_p2.Models.EntradaDetalle", b =>
                {
                    b.HasOne("Eddian_Vasquez_Ap1_p2.Models.Entrada", "Entrada")
                        .WithMany("Detalle")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eddian_Vasquez_Ap1_p2.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrada");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Eddian_Vasquez_Ap1_p2.Models.Entrada", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
